// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: internal/core/proto/pty.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PTYShell_Shell_FullMethodName = "/PTYShell/Shell"
)

// PTYShellClient is the client API for PTYShell service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PTYShellClient interface {
	Shell(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ShellData, ShellData], error)
}

type pTYShellClient struct {
	cc grpc.ClientConnInterface
}

func NewPTYShellClient(cc grpc.ClientConnInterface) PTYShellClient {
	return &pTYShellClient{cc}
}

func (c *pTYShellClient) Shell(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ShellData, ShellData], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PTYShell_ServiceDesc.Streams[0], PTYShell_Shell_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ShellData, ShellData]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PTYShell_ShellClient = grpc.BidiStreamingClient[ShellData, ShellData]

// PTYShellServer is the server API for PTYShell service.
// All implementations must embed UnimplementedPTYShellServer
// for forward compatibility.
type PTYShellServer interface {
	Shell(grpc.BidiStreamingServer[ShellData, ShellData]) error
	mustEmbedUnimplementedPTYShellServer()
}

// UnimplementedPTYShellServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPTYShellServer struct{}

func (UnimplementedPTYShellServer) Shell(grpc.BidiStreamingServer[ShellData, ShellData]) error {
	return status.Errorf(codes.Unimplemented, "method Shell not implemented")
}
func (UnimplementedPTYShellServer) mustEmbedUnimplementedPTYShellServer() {}
func (UnimplementedPTYShellServer) testEmbeddedByValue()                  {}

// UnsafePTYShellServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PTYShellServer will
// result in compilation errors.
type UnsafePTYShellServer interface {
	mustEmbedUnimplementedPTYShellServer()
}

func RegisterPTYShellServer(s grpc.ServiceRegistrar, srv PTYShellServer) {
	// If the following call pancis, it indicates UnimplementedPTYShellServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PTYShell_ServiceDesc, srv)
}

func _PTYShell_Shell_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PTYShellServer).Shell(&grpc.GenericServerStream[ShellData, ShellData]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PTYShell_ShellServer = grpc.BidiStreamingServer[ShellData, ShellData]

// PTYShell_ServiceDesc is the grpc.ServiceDesc for PTYShell service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PTYShell_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "PTYShell",
	HandlerType: (*PTYShellServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Shell",
			Handler:       _PTYShell_Shell_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "internal/core/proto/pty.proto",
}
